
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author PC
 */
public class Conversor extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Conversor.class.getName());

    /**
     * Creates new form Conversor
     */
    public Conversor() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tipoDeTemperatura = new javax.swing.ButtonGroup();
        title = new javax.swing.JLabel();
        subtitle = new javax.swing.JLabel();
        txtTemperatura = new javax.swing.JTextField();
        btnConvertir = new javax.swing.JButton();
        btnRaFahrenheit = new javax.swing.JRadioButton();
        btnRaKelvin = new javax.swing.JRadioButton();
        btnRaRadianes = new javax.swing.JRadioButton();
        btnRaCelcius = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        title.setText("Conversor de temperatura");
        title.setMinimumSize(new java.awt.Dimension(400, 75));

        subtitle.setText("Ingrese temperatura en grados");

        txtTemperatura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTemperaturaActionPerformed(evt);
            }
        });

        btnConvertir.setText("Convertir");
        btnConvertir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConvertirActionPerformed(evt);
            }
        });

        tipoDeTemperatura.add(btnRaFahrenheit);
        btnRaFahrenheit.setText("A Fahrenheit");
        btnRaFahrenheit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRaFahrenheitActionPerformed(evt);
            }
        });

        tipoDeTemperatura.add(btnRaKelvin);
        btnRaKelvin.setText("A Kelvin");
        btnRaKelvin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRaKelvinActionPerformed(evt);
            }
        });

        tipoDeTemperatura.add(btnRaRadianes);
        btnRaRadianes.setText("A Radianes");

        tipoDeTemperatura.add(btnRaCelcius);
        btnRaCelcius.setText("A Celcius");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnRaRadianes)
                            .addComponent(btnRaFahrenheit))
                        .addGap(95, 95, 95)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnRaKelvin)
                            .addComponent(btnRaCelcius)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(subtitle))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(txtTemperatura, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(btnConvertir, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(78, 109, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(subtitle)
                .addGap(18, 18, 18)
                .addComponent(txtTemperatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(btnRaFahrenheit))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnRaKelvin)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRaRadianes)
                    .addComponent(btnRaCelcius))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(btnConvertir, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtTemperaturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTemperaturaActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtTemperaturaActionPerformed

    private void btnRaFahrenheitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRaFahrenheitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRaFahrenheitActionPerformed

    private void btnRaKelvinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRaKelvinActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnRaKelvinActionPerformed

    private void btnConvertirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConvertirActionPerformed
        // TODO add your handling code here:
        
        double resultado = 0;
        
        try {
        if(txtTemperatura.getText().equals("")){
            
            String message="ingrese algun numero entero";
            JOptionPane.showMessageDialog(
                this,
                message,
                "ERROR",
                JOptionPane.INFORMATION_MESSAGE
        );
        }else if(btnRaKelvin.isSelected()==true){
            
            
            
            resultado = (Integer.parseInt(txtTemperatura.getText()) +273.5);
            JOptionPane.showMessageDialog(
                this,
                "a kelvin: "+resultado+" Kº",
                "MENSAJE",
                JOptionPane.INFORMATION_MESSAGE
        );
        }else if(btnRaFahrenheit.isSelected()==true){
            
            
            
            resultado = (Integer.parseInt(txtTemperatura.getText()) *9)/5+32;
            JOptionPane.showMessageDialog(
                this,
                "a faharenheit: "+resultado+" Fº",
                "MENSAJE",
                JOptionPane.INFORMATION_MESSAGE
        );
        }else if(btnRaRadianes.isSelected()==true){
            
            
            
            String rad = txtTemperatura.getText();
            JOptionPane.showMessageDialog(
                this,
                "a radianes: " + Integer.parseInt(rad) * 3.14 / 180 + " rad",
                "MENSAJE",
                JOptionPane.INFORMATION_MESSAGE
        );
        }else if(btnRaCelcius.isSelected()==true){
            
            
            
            String cel =txtTemperatura.getText();
            JOptionPane.showMessageDialog(
                this,
                "a celcius: "+cel +"Cº",
                "MENSAJE",
                JOptionPane.INFORMATION_MESSAGE
        );
        }
        } catch (NumberFormatException e) {
            String message="ingresó un valor no válido";
            JOptionPane.showMessageDialog(
                this,
                message,
                "ERROR",
                JOptionPane.INFORMATION_MESSAGE
        );
        }
        
        
        
    }//GEN-LAST:event_btnConvertirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Conversor().setVisible(true));
    }
    private void convertir(){
       
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConvertir;
    private javax.swing.JRadioButton btnRaCelcius;
    private javax.swing.JRadioButton btnRaFahrenheit;
    private javax.swing.JRadioButton btnRaKelvin;
    private javax.swing.JRadioButton btnRaRadianes;
    private javax.swing.JLabel subtitle;
    private javax.swing.ButtonGroup tipoDeTemperatura;
    private javax.swing.JLabel title;
    private javax.swing.JTextField txtTemperatura;
    // End of variables declaration//GEN-END:variables
}
